"""Add login lockout fields

Revision ID: 363b9a5c9ef2
Revises: 
Create Date: 2026-08-12 10:02:58.467473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363b9a5c9ef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'users',
        sa.Column(
            'failed_attempts',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'locked_until',
            sa.DateTime(),
            nullable=True
        )
    )

    op.alter_column(
        'users',
        'failed_attempts',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_attempts')
    # ### end Alembic commands ###
